### ISSUE TITLE
explosionCreator error

### ISSUE THREAD

**Issue by sladkiimaksimka** [mestiez/ppg-snippets#15]
a error in 
ExplosionCreator.Explode(new ExplosionCreator.ExplosionParameters
{
    //Explosion center
    >Position = transform.position,

**Comment by sladkiimaksimka** [comment]
![Безымянный](https://user-images.githubusercontent.com/99991427/154744072-32da89a4-36b3-4317-933a-3e663bf4e9a1.png)

**Comment by TheCoderLicer** [comment]
there seems to be an error with transform, sadly IDK what it is because there are boxes blocking it.

**Comment by sladkiimaksimka** [comment]
I fixed it, and I didn't understand how
