### ISSUE TITLE
can you show me how to make an advanced weapon and also how to make a flamethrower please

### ISSUE THREAD

**Issue by Galtord** [mestiez/ppg-snippets#19]
I also need to make a few for the same mod can you also show how to make a flamethrower please I need it

**Comment by R0Y1T0** [comment]
Just use the "adding a new gun" snippet and instead of deriving from the pistol change it to Flamethrower.
About the advanced weapon u should check studiominus tutorial, but i don't understand what's an advanced weapon for you, explain.

**Comment by Kubaadamlec** [comment]
https://www.studiominus.nl/ppg-modding/tutorials/tutorialCustomGunAdvanced.html
