### ISSUE TITLE
Load videos 

### ISSUE THREAD

**Issue by R0Y1T0** [mestiez/ppg-snippets#26]
i know i'm posting a lot here, but i'm trying to work on other things, what's the definition to load videos? I tried using
`ModAPI.LoadVideo`
or
`ModAPI.LoadBroadcast`
but these didn't work (don't exist), and i'm trying to make a custom TV transmission

**Comment by mestiez** [comment]
videos **cannot** be loaded as of 1.23

**Comment by R0Y1T0** [comment]
oh, thanks for the anwser
