### ISSUE TITLE
How to increase human sprite size

### ISSUE THREAD

**Issue by ghost** [mestiez/ppg-snippets#54]
Hi, I have been scouring on how to do this for days now, but is there a way to increase the sprite size of a human? Because if I expand the image anything above the default sprite size is not registered and is invisible.

**Comment by Galtord** [comment]
example:

     //new human
    ModAPI.Register(
    new Modification()
    {
        OriginalItem = ModAPI.FindSpawnable("Human"),
        NameOverride = "new human",
        NameToOrderByOverride = "human",
        DescriptionOverride = "new human description",
        CategoryOverride = ModAPI.FindCategory("Entities"),
        ThumbnailOverride = ModAPI.LoadSprite("icon new human.png"),
        AfterSpawn = (Instance) =>
        {
            //load textures for each layer (see Human textures folder in this repository)
            var skin = ModAPI.LoadTexture("Skin new human.png");
            var flesh = ModAPI.LoadTexture("Flesh new human.png");
            var bone = ModAPI.LoadTexture("Bone new human.png");

            //get person
            var person = Instance.GetComponent<PersonBehaviour>();

            //use the helper function to set each texture
            //parameters are as follows: 
            //  skin texture, flesh texture, bone texture, sprite scale
            //you can pass "null" to fall back to the original texture
            person.SetBodyTextures(skin, flesh, bone, 2);

            //change procedural damage colours if they interfere with your texture (rgb 0-255)
            person.SetBruiseColor(143, 0, 0);
            person.SetSecondBruiseColor(82, 0, 0);
            person.SetThirdBruiseColor(43, 0, 0);
            person.SetRottenColour(71, 89, 50);
            person.SetBloodColour(75, 0, 0);
                    }
                }
            );

**Comment by Galtord** [comment]
please if you use this you can put a comment with the name of your mod to my mod called left 4 dead mod my name is The Galtor on steam

**Comment by Galtord** [comment]
link of my mod https://steamcommunity.com/sharedfiles/filedetails/?id=2872728902

**Comment by ghost** [comment]
thank you so much!
