### ISSUE TITLE
I have this error with the mod I made

### ISSUE THREAD

**Issue by dogefan99991** [mestiez/ppg-snippets#56]
![IMG_2112](https://github.com/mestiez/ppg-snippets/assets/121646734/4780afa1-eb77-4fb0-9a08-c9d9a2cb74a8)

**Comment by dogefan99991** [comment]
some please help me

**Comment by Galtord** [comment]
That error never happened to me so I'm going to tell you that you could use a technique that sometimes works for me called trial and error, which consists of changing something, trying it and if it doesn't work, changing something again until it works or see what it happens in one of the columns as it says there where it says at 27.14
