### ISSUE TITLE
what function makes objects freeze?

### ISSUE THREAD

**Issue by skeyvin** [mestiez/ppg-snippets#6]
ModAPI.OnItemSelected += (sender, phys) => {
   object = phys;
};
with this i get what object is selected
how do i go about freezing this as you would in the right click menu?
also is it possible to know object is under the cursor?
i didnt find the answer in the docs

**Comment by mestiez** [comment]
There is no one function to freeze an object as if the user froze it.

The game does 
```cs
if (phys.PlaySliderSound && phys.slidingAudioSource)
   phys.slidingAudioSource.Stop();

phys.gameObject.AddComponent<FreezeBehaviour>();
phys.gameObject.BroadcastMessage(nameof(Messages.IOnUserFreeze.OnUserFreeze), SendMessageOptions.DontRequireReceiver);
```
