### ISSUE TITLE
Human mod snippet just becomes error when compiling

### ISSUE THREAD

**Issue by YouTubeSnickerdoodle** [mestiez/ppg-snippets#7]
my mod after compiling just says
Modcompiler, { expected at 5,13
Type or namespace definiton, or end-of-fie expected at 6,0
{ expected at 7,17
}expected at 7,17
; expected at 9,27

**Comment by GaminglikiwitherYT** [comment]
Same, I dont know why it happens please fix this ASAP. It says error for me too.

**Comment by BBQGiraffe** [comment]
please send your code
